"""Deterministic synthetic PCAPs and independently authored pilot labels."""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import struct

from dfilterforge.evaluation import ProbeExpectationV1
from dfilterforge.evaluation import SemanticSpecV1
from dfilterforge.intent_ir import All
from dfilterforge.intent_ir import IntentIrV1
from dfilterforge.intent_ir import Operator
from dfilterforge.intent_ir import Predicate

_SEEDS = (17, 42, 2026)
_TCP_FLAGS = {
    "syn": 2,
    "syn-ack": 18,
    "ack": 16,
    "ecn-syn": 194,
    "reset": 20,
    "fin": 1,
}
_PROVENANCE = (
    "Synthetic Ethernet/IPv4 packets generated by dfilterforge.fixtures v1; "
    "independently authored packet labels; seeds 17, 42, 2026. "
    "Review covers packet recipes and labels; tshark agreement is a separate "
    "execution gate. No captured user traffic."
)


@dataclass(frozen=True)
class _ProbePlan:
    seed: int
    packets: tuple[str, ...]
    expected_frames: tuple[int, ...]
    near_wrong_frames: tuple[int, ...]


@dataclass(frozen=True)
class _CasePlan:
    task_id: str
    intent: str
    canonical_ir: IntentIrV1
    reference_filter: str
    near_wrong_filter: str
    probes: tuple[_ProbePlan, ...]


def _case_plans() -> tuple[_CasePlan, ...]:
    """Defines packet sets directly, without running or evaluating filters."""
    return (
        _CasePlan(
            "tcp-syn-no-ack",
            "Show TCP packets with SYN set and ACK clear, including ECN SYN.",
            IntentIrV1(
                expression=All(
                    children=(
                        Predicate(
                            field="tcp.flags.syn",
                            operator=Operator.EQ,
                            value=True,
                        ),
                        Predicate(
                            field="tcp.flags.ack",
                            operator=Operator.EQ,
                            value=False,
                        ),
                    )
                )
            ),
            "tcp.flags.syn == true && tcp.flags.ack == false",
            "tcp.flags.syn == true",
            (
                _ProbePlan(
                    17,
                    ("syn", "syn-ack", "ack", "udp-query", "fin"),
                    (1,),
                    (1, 2),
                ),
                _ProbePlan(
                    42,
                    ("ack", "syn-ack", "syn", "ecn-syn", "udp-other", "reset"),
                    (3, 4),
                    (2, 3, 4),
                ),
                _ProbePlan(
                    2026,
                    ("udp-query", "syn-ack", "ack", "syn", "syn-ack", "syn"),
                    (4, 6),
                    (2, 4, 5, 6),
                ),
            ),
        ),
        _CasePlan(
            "dns-udp-query",
            "Show DNS query packets transported over UDP, excluding responses.",
            IntentIrV1(
                expression=All(
                    children=(
                        Predicate(field="udp", operator=Operator.EXISTS),
                        Predicate(
                            field="dns.flags.response",
                            operator=Operator.EQ,
                            value=False,
                        ),
                    )
                )
            ),
            "udp && dns.flags.response == false",
            "udp && dns",
            (
                _ProbePlan(
                    17,
                    (
                        "udp-query",
                        "udp-response",
                        "udp-query",
                        "udp-other",
                        "tcp-query",
                    ),
                    (1, 3),
                    (1, 2, 3),
                ),
                _ProbePlan(
                    42,
                    ("udp-response", "tcp-query", "udp-query", "udp-query"),
                    (3, 4),
                    (1, 3, 4),
                ),
                _ProbePlan(
                    2026,
                    (
                        "udp-other",
                        "udp-query",
                        "udp-response",
                        "tcp-query",
                        "udp-query",
                    ),
                    (2, 5),
                    (2, 3, 5),
                ),
            ),
        ),
        _CasePlan(
            "udp-destination-53",
            "Show UDP packets whose destination port is 53, "
            "regardless of source port.",
            IntentIrV1(
                expression=Predicate(
                    field="udp.dstport",
                    operator=Operator.EQ,
                    value=53,
                )
            ),
            "udp.dstport == 53",
            "udp.port == 53",
            (
                _ProbePlan(
                    17,
                    ("udp-query", "udp-response", "udp-other", "tcp-query"),
                    (1,),
                    (1, 2),
                ),
                _ProbePlan(
                    42,
                    (
                        "udp-response",
                        "udp-both-53",
                        "udp-query",
                        "tcp-query",
                        "udp-other",
                    ),
                    (2, 3),
                    (1, 2, 3),
                ),
                _ProbePlan(
                    2026,
                    (
                        "tcp-query",
                        "udp-response",
                        "udp-other",
                        "udp-query",
                        "udp-response",
                        "udp-both-53",
                    ),
                    (4, 6),
                    (2, 4, 5, 6),
                ),
            ),
        ),
    )


def _checksum(payload: bytes) -> int:
    """Computes the Internet checksum over bytes in network order."""
    padded = payload + (b"\0" if len(payload) % 2 else b"")
    total = sum(struct.unpack(f"!{len(padded) // 2}H", padded))
    while total >> 16:
        total = (total & 0xFFFF) + (total >> 16)
    return (~total) & 0xFFFF


def _dns_message(seed: int, ordinal: int, response: bool) -> bytes:
    """Builds a DNS A question, optionally in a successful empty response."""
    labels = (f"probe-{seed}-{ordinal}".encode("ascii"), b"example")
    question = b"".join(bytes((len(label),)) + label for label in labels)
    header = struct.pack(
        "!6H",
        seed + ordinal,
        0x8180 if response else 0x0100,
        1,
        0,
        0,
        0,
    )
    return header + question + b"\0" + struct.pack("!HH", 1, 1)


def _transport_packet(
    recipe: str,
    seed: int,
    ordinal: int,
    source: bytes,
    destination: bytes,
) -> tuple[int, bytes]:
    """Builds a TCP or UDP segment, including its pseudo-header checksum."""
    source_port = 41000 + seed + ordinal
    destination_port = 443
    payload = b""
    is_tcp = recipe in _TCP_FLAGS or recipe == "tcp-query"
    if recipe in {"udp-query", "udp-response", "tcp-query", "udp-both-53"}:
        destination_port = 53
        payload = _dns_message(seed, ordinal, recipe == "udp-response")
        if recipe == "udp-response":
            source_port, destination_port = destination_port, source_port
        elif recipe == "udp-both-53":
            source_port = 53
        elif recipe == "tcp-query":
            payload = struct.pack("!H", len(payload)) + payload
    elif recipe == "udp-other":
        destination_port = 9999
        payload = f"synthetic-{seed}-{ordinal}".encode("ascii")
    if is_tcp:
        protocol = 6
        flags = _TCP_FLAGS.get(recipe, 24)
        segment = (
            struct.pack(
                "!HHIIBBHHH",
                source_port,
                destination_port,
                seed * 100 + ordinal,
                1 if flags & 16 else 0,
                0x50,
                flags,
                8192,
                0,
                0,
            )
            + payload
        )
        checksum_offset = 16
    else:
        protocol = 17
        segment = (
            struct.pack(
                "!HHHH",
                source_port,
                destination_port,
                len(payload) + 8,
                0,
            )
            + payload
        )
        checksum_offset = 6
    pseudo = (
        source + destination + struct.pack("!BBH", 0, protocol, len(segment))
    )
    checksum = _checksum(pseudo + segment) or 0xFFFF
    segment = (
        segment[:checksum_offset]
        + struct.pack("!H", checksum)
        + segment[checksum_offset + 2 :]
    )
    return protocol, segment


def _ethernet_packet(recipe: str, seed: int, ordinal: int) -> bytes:
    source = bytes((192, 0, 2, seed % 200 + 1))
    destination = bytes((198, 51, 100, ordinal))
    protocol, segment = _transport_packet(
        recipe, seed, ordinal, source, destination
    )
    header = struct.pack(
        "!BBHHHBBH4s4s",
        0x45,
        0,
        len(segment) + 20,
        seed + ordinal,
        0x4000,
        64,
        protocol,
        0,
        source,
        destination,
    )
    header = header[:10] + struct.pack("!H", _checksum(header)) + header[12:]
    ethernet = bytes.fromhex("0200000000020200000000010800")
    return (ethernet + header + segment).ljust(60, b"\0")


def _capture_bytes(probe: _ProbePlan) -> bytes:
    """Serializes little-endian microsecond PCAP with Ethernet link type."""
    records = [struct.pack("<IHHIIII", 0xA1B2C3D4, 2, 4, 0, 0, 65535, 1)]
    for ordinal, recipe in enumerate(probe.packets, 1):
        packet = _ethernet_packet(recipe, probe.seed, ordinal)
        records.append(
            struct.pack(
                "<IIII",
                1700000000 + probe.seed,
                ordinal * 1000,
                len(packet),
                len(packet),
            )
        )
        records.append(packet)
    return b"".join(records)


def _write_json(path: Path, payload: object) -> str:
    encoded = (json.dumps(payload, sort_keys=True, indent=2) + "\n").encode(
        "utf-8"
    )
    path.write_bytes(encoded)
    return hashlib.sha256(encoded).hexdigest()


def _generate_case(output_dir: Path, case: _CasePlan) -> dict[str, object]:
    expectations: list[ProbeExpectationV1] = []
    probes: list[dict[str, object]] = []
    for probe in case.probes:
        probe_id = f"{case.task_id}-{probe.seed}"
        capture_path = f"captures/{probe_id}.pcap"
        capture = _capture_bytes(probe)
        (output_dir / capture_path).write_bytes(capture)
        capture_hash = hashlib.sha256(capture).hexdigest()
        expectations.append(
            ProbeExpectationV1(
                probe_id=probe_id,
                capture_sha256=capture_hash,
                expected_frames=probe.expected_frames,
            )
        )
        probes.append(
            {
                "probe_id": probe_id,
                "seed": probe.seed,
                "capture_path": capture_path,
                "capture_sha256": capture_hash,
                "packet_count": len(probe.packets),
                "packet_recipes": probe.packets,
                "expected_frames": probe.expected_frames,
                "near_wrong_frames": probe.near_wrong_frames,
            }
        )
    spec = SemanticSpecV1(
        task_id=case.task_id,
        intent=case.intent,
        assumptions=(
            "Packet-scoped Ethernet/IPv4 pilot with complete "
            "synthetic packets.",
            "Equivalence claims apply only to the recorded probes "
            "and environment.",
        ),
        canonical_ir=case.canonical_ir,
        reference_filter=case.reference_filter,
        probes=tuple(expectations),
        split="pilot",
        provenance=_PROVENANCE,
        license="MIT",
        review_status="reviewed",
    )
    spec_path = f"specs/{case.task_id}.json"
    intent_path = f"intents/{case.task_id}.json"
    spec_hash = _write_json(
        output_dir / spec_path, spec.model_dump(mode="json")
    )
    intent_hash = _write_json(
        output_dir / intent_path,
        case.canonical_ir.model_dump(mode="json"),
    )
    return {
        "task_id": case.task_id,
        "spec_path": spec_path,
        "spec_sha256": spec_hash,
        "intent_path": intent_path,
        "intent_sha256": intent_hash,
        "near_wrong_filter": case.near_wrong_filter,
        "probes": probes,
    }


def generate_fixtures(output_dir: Path) -> Path:
    """Writes three curated semantic tasks and nine reproducible probe captures.

    Every frame label is authored in the packet plan independently of the
    reference filter and compiler. Existing generated files are replaced;
    unrelated files in the output directory are preserved.

    Args:
        output_dir: Directory for captures, specs, intents, and manifest.json.

    Returns:
        The manifest path. All paths within the manifest are relative to its
        directory; capture filenames are exactly ``{probe_id}.pcap``.
    """
    for directory in ("captures", "specs", "intents"):
        (output_dir / directory).mkdir(parents=True, exist_ok=True)
    manifest = {
        "schema_version": "1.0",
        "generator": "dfilterforge.fixtures/v1",
        "seeds": _SEEDS,
        "split": "pilot",
        "license": "MIT",
        "provenance": _PROVENANCE,
        "review_status": "reviewed",
        "cases": [_generate_case(output_dir, case) for case in _case_plans()],
    }
    manifest_path = output_dir / "manifest.json"
    _write_json(manifest_path, manifest)
    return manifest_path
